language: rust
sudo: false
cache: cargo
rust:
- stable
before_script:
- "(test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)"
- (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.1" mdbook)
- cargo install-update -a
script:
- mdbook build && mdbook test
deploy:
  provider: pages
  skip_cleanup: true
  token: "$GITHUB_TOKEN"
  local_dir: "./book"
  keep_history: true
  on:
    branch: master
env:
  global:
  - secure: lXC1vzQcKodc8pAeC5bx5MgtLiigm9WV4qcqX8yzT7e52tW8N68Yjl08un8jDY3xLwrFmZY6JVYRYGNI+k0lQUsko1b276U4OpwSulHKaArKrLOv/EWbbG76YM/E4yf1/sLzrrZ9Kus/x4Xb2U2uWGmdVKMVMWtRqhZJcdEST4Syzclg0GsBlmdYnFlDFYRjRcftwpxyhtzpfZUoV9vdkiAMKczPkkkt9Cq6eEmQjZpUDfaWN7sYBqeS2vX8CcBPlucbKKLUNldmUckClN6dzKpJ+tWgoMJTbYXvRxt41D2a/1PlQ1XtM2ALP6mUOsyBuGYwEqDYSsZI3LC7omTgUBR0EUjJFDaXKpl6DaRT1md18elVeIg3pb+j2cBmdoxPEbJCq26ns7r3RY2Kpfw71BPDjvyqmisyT2MTiU0MduMJrFfj3C/dTua3ZDZ5Qk2lnedzd7NLN/KUnulpJ1HwHSK2op0TWijU5L+t9OWdI7J0GDWIMHK3q2GuBcu1PWGU1+JWnx7ZEhu6b10niXu3CkK69gF+V1ipLVMA0tXQx7CH3khaTlAbaaQiTLzI/nMwkw3WmDtU1z6Ao9hxMzGLFzy1Vb/2cx+rIP8F6Y//b3W730XSqf6Xvyp/FPC3IHQb0TswHhhyJzYVW1K+VYq+DBNMJMYHsmBlKpCCUsBae+M=
  - secure: ebzz1wbHL1kOIhYdPNUH4GsjTFW4yNaOWrKP1NSuz1+lZCaVVsXbVK8YKioPG0vW5e4RGc9dwWXW0Tdq1M2kWVk/3mSjPMGYgv3flqBenPIjYzIDuZQwgZfqKgM/6PeCIoSe3XVrhmfX5C4UN6ttklNjKnwIAMF/VluEqVmGQLxGhtf0rXHuUxh8qfEiXC1Y4L1tWFN7XWe9onSCz1TOLx/9gwKuBD3UAf8OzPO99DYNQGQCepd1H3nSvEMA+X7ksgOH/Xd208XTnJtQhmb/GVQ4h617diJ9W4Nx4j6HahVjxvTXG08rYlEsxzNjoJfsOcFrIsfQKpC9z6HMkSn/AtMLBoKCT4rXZXdQmjcTs0YV0ExK2M07lw1uZAG4vKpWuaZr93NVTtOUDnSgqnHRTJRQBw7CPwog4uGuxRYtQ9RHd0UQm2BskAT5u2RI95PC834BAm2jERUhfYYJtsAGD6QwvBXJgHegjo+f+TezsTW89oYajFMctmYbtdRFrm7k5iHyg6oUAbyGdzjzmkwjKvNfta3/3SALOODsjqWQ+5tawMuc5BCM8x7mH2sj0tzxEsyNT82UnHmVYWbij8gSCtudZlR9bmZkatr21K4YqvTnv9o3S323KWtuN6D16uW7VPSUfSiHf9cheGN3+9L+YRT9+ZhorF+m59F3ApXrSy8=
